### ISSUE TITLE
Support the special single element version of lists

### ISSUE THREAD

**Issue by sorenbs** [supergraphql/graphql-static-binding#10]
GraphQL support single element lists to be written as if they were an object. Ie, these are equivalent:

```graphql
data: { progress: { create: [{ message }] } }
```

```graphql
data: { progress: { create: { message } } }
```

It would be great if the generated binding could support this as well

**Comment by kbrandwijk** [comment]
@sorenbs As far as I can see, this only applies to input types, right?
