### ISSUE TITLE
Implement exists for Graphcool bindings

### ISSUE THREAD

**Issue by kbrandwijk** [supergraphql/graphql-static-binding#11]

**Comment by schickling** [comment]
Would be great to have this soon! 🎉

**Comment by kbrandwijk** [comment]
Do we have final consensus on the API?

1. `context.db.Post.exists(...)`
2. `context.db.posts.exists(...)`
3. `context.exists.Post(...)`
4. `context.exists.posts(...)`

(1) is my personal favorite (by Type name, not query root field).

**Comment by schickling** [comment]
For now it will be (4) until we've found a new Binding API design (see https://github.com/graphcool/graphcool-binding/issues/11)

**Comment by kbrandwijk** [comment]
After some consideration, the current PR is for option (3), with a corresponding PR on `graphcool-binding` to implement identical behavior for dynamic bindings. See https://github.com/graphcool/graphcool-binding/pull/34.
