### ISSUE TITLE
consider aliasing ID type to string only

### ISSUE THREAD

**Issue by sorenbs** [supergraphql/graphql-static-binding#12]
Currently the ID type alias to string | number:

```ts
/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID = string | number
```

This makes sense, but has the unfortunate consequence of making it more difficult to pass the id around internally:

![image](https://user-images.githubusercontent.com/281337/34447313-e64d0f68-ece2-11e7-8115-de456be7d711.png)

I'm not sure this should change, but wanted to bring it up

**Comment by kbrandwijk** [comment]
I think the same solution could be applied as for #10. Splitting the ID type, and having an InputId and OutputID type, with `string | number` and `string` respectively.

**Comment by sorenbs** [comment]
I like this approach 👍
