### ISSUE TITLE
Add TSLint:Disable to generated/graphcool.ts 

### ISSUE THREAD

**Issue by kbrandwijk** [supergraphql/graphql-static-binding#32]
_From @philcockfield on January 8, 2018 17:48_

With GraphCool 1.0 a TypeScript file is generated locally after deploy:

    /src/generated/graphcool.ts

This produces typescript that may conflict with the projects `tslint.json` rules.
Can you include a 

    // tslint:disable

directive at the top of the generated file to exclude it from the projects linting output, please?

Thanks.

_Copied from original issue: graphcool/graphcool#1543_

**Comment by kbrandwijk** [comment]
TSLint also offers a configuration option to ignore a certain folder (in this case: generated), either using the `--exclude` command line option, of the `exclude` node in your `tsconfig.json`.

I think that would be a better solution than adding these types of statements to the files.Tslint is not the only linter out there, and I don't want to end up with 10 different ignore statements in my generated files.

**Comment by philcockfield** [comment]
Yeah, that's probably better given your rationale of there being more than one linter out there.

**Comment by philcockfield** [comment]
>> exclude node in your tsconfig.json

That wouldn't work - as you actually want the files to be transpiled, just not linted.  I've added an `--exclude` to the tslint command.

**Comment by kbrandwijk** [comment]
@philcockfield Sorry, I meant `tslint.json` not `tsconfig.json`...

```json
"cliOptions": {
  "exclude": [
    "src/generated",
  ]
}
```

**Comment by kbrandwijk** [comment]
Closing this, as the alternative to configure this for tslint is known, and I'm not going to put something in the generated file.
